name: Convert PHP to Static HTML
on:
  push:
    branches:
      - main
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget

      - name: Run wget to convert PHP to HTML
        run: |
          wget --mirror --convert-links --adjust-extension --page-requisites --no-parent http://localhost:8000

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./localhost
